apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-demo
  labels:
    app: ping
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: ping
    spec:
      containers:
      - name: ping
        image: ghcr.io/azamatkomaev/argo-image-updater-demo:d0400390a3fc79ffed3991d9b473d3faccd26c1e
        ports:
        - containerPort: 8080
